### ISSUE TITLE
Bump react-scripts peer dependency to support v3

### ISSUE THREAD

**Issue by feimosi** [harrysolovay/rescripts#49] opened 2019-05-29 10:14 UTC
I'm using `@rescripts/cli@0.0.10` with `react-scripts@3.0.1` without any issues. Could you update the peer dependency version range?

**Comment by harrysolovay** [comment] 2019-05-29 19:02
@feimosi what do you mean by "update the peer dependency range?" Can you please elaborate.

**Comment by feimosi** [comment] 2019-05-29 22:39
You can use a range to support both major versions, e.g.: `2.x - 3.x`
Test it here: https://semver.npmjs.com

**Comment by tjma2001** [comment] 2019-05-30 14:16
We are getting this when installing the CLI 

<img width="666" alt="image" src="https://user-images.githubusercontent.com/8049309/58638987-53bd6e80-82f6-11e9-9356-4a584f4a125a.png">

**Comment by Pavel910** [comment] 2019-05-31 19:53
I can confirm everything is working with `react-scripts@^3`, but yes, the warning mentioned by @tjma2001 does pop up.

**Comment by zeorin** [comment] 2019-06-03 10:50
There are a bunch of these for me:
```
warning " > @rescripts/cli@0.0.10" has incorrect peer dependency "react-scripts@^2.1.2".
warning "@rescripts/cli > @rescripts/utilities@0.0.5" has incorrect peer dependency "react-scripts@^2.1.2".
warning "@rescripts/rescript-env > @rescripts/rescript-use-tslint-config > tslint-loader@3.5.4" has unmet peer dependency "tslint@>=4.0.0".
```

**Comment by harrysolovay** [comment] 2019-06-03 16:49
My sense is that this is a pretty common (and in this case, innocuous) class of warning. Please correct me if I'm wrong––I'm committed to making sure Rescripts is safe. Open to PRs.

**Comment by zeorin** [comment] 2019-06-03 19:30
The peer dependency is meant to indicate which versions of packages a package should be used _with_, it just doesn't depend on them in the sense of importing or requiring them.

However, the version ranges expressed ought to be taken just as seriously as those of other dependencies.

If the package happens to work with versions above the range expressed for the peer dependencies, great! But then the version range needs to be adjusted.

Also, personally I don't like seeing _any_ warnings from any of my devtools, because aim to get a very high signal-to-noise ratio from them. If many packages have "harmless" peer dependency mismatch warnings, how am I going to spot the one that matters? If I actually need to fix such an issue, all the others are in my way and working against me.

It is recommended that the version ranges for peerdependencies are as permissive as they can safely be.

**Comment by zeorin** [comment] 2019-06-03 19:32
I'll happily create a PR if you provide the ranges for the peerDependencies which are safe for your packages.

**Comment by harrysolovay** [comment] 2019-06-03 19:35
@zeorin –– I believe this package works with the latest `react-scripts` (3.0.1)

**Comment by zeorin** [comment] 2019-06-03 20:09
Ok, but what about the next versions? Can I assume that it will be compatible with all ^3 versions?

Perhaps this is a good time to think about a versioning scheme that makes sense for all the official rescripts packages. Some projects will lock all compatible packages to the same major version.

The point I was obtusely trying to make with my previous flippant comment is that this is one of the  things that a drive-by contributor is ill-suited to make and only the package maintainers are well suited to. The work for such a PR isn't in physically updating the version numbers. It's in deciding what to update them to.

**Comment by feimosi** [comment] 2019-06-03 23:35
As `rescripts` is changing some internal CRA behavior, any update could potentially break it. However, if you already use such a tool, you should be familiar with the risks involved. Therefore I would allow any v3 as a peerDependency. Can't imagine the maintainer testing every new CRA release, bumping the version range and releasing a new `rescripts` update. That's my opinion.

**Comment by zeorin** [comment] 2019-06-05 10:00
> As rescripts is changing some internal CRA behavior, any update could potentially break it.
The person that has the most insight into what internal behaviour rescripts depends upon is the maintainer. Based on that knowledge and a review of react-scripts' versioning policy, they're best positioned to decide the compatibility range.

> Can't imagine the maintainer testing every new CRA release, bumping the version range and releasing a new rescripts update.
That can be automated. Any time that CRA commits to master, re-run a test setup of rescripts. If it fails, ping the maintainer/create an issue.

**Comment by feimosi** [comment] 2019-06-05 10:15
True, it's up to the maintainer. If he can automate it that'd be great. I'm happy with any solution that addresses this issue.

**Comment by harrysolovay** [comment] 2019-06-10 17:43
Hi @zeorin & @feimosi –– apologies for being out of touch. My job has distracted me from being as engaged as I'd like to be.

It really excites me to see this conversation, and I'm wondering if either of you are interested in becoming maintainers?

**Comment by feimosi** [comment] 2019-06-16 12:45
@harrysolovay I wish I could help out with maintaining this great project but unfortunately I'm very busy these days.

**Comment by harrysolovay** [comment] 2019-06-19 21:43
@feimosi no worries. Same boat here.

**Closed** 2019-09-07 08:52 UTC
